<?php
/*  
Copyright: © 2010 Haden Software <http://haden.cc/>

Released under the terms of the GNU General Public License.
You should have received a copy of the GNU General Public License,
along with this software. In the main directory, see: /licensing/
If not, see: <http://www.gnu.org/licenses/>.
*/

/**************************************************************************************************/ 
/* WARNING: This is a system configuration file, please DO NOT EDIT this file directly!           */
/**************************************************************************************************/

/**************************************************************************************************/
/* This file contain functions used to configure the options and $GLOBALS variable                */
/* Functions provided:                                                                            */
/*  hsmember_configure_options_defaults - Return with the default values of the options.          */
/*  hsmember_configure_options_validate - Validate the passed options, substituting them with     */
/*                                        defaults if corrupted.                                  */
/*  hsmember_configure_options_init     - Loads the initial values of the options from the data   */
/*                                        tables                                                  */
/**************************************************************************************************/

/**************************************************************************************************/
/* Direct access denial.                                                                          */
/**************************************************************************************************/
if (realpath (__FILE__) === realpath ($_SERVER["SCRIPT_FILENAME"]))
	exit ("Do not access this file directly.");

/**************************************************************************************************/
/* Function to provide default option values.                                                     */
/* Return Value:                                                                                  */
/*  The default options.                                                                          */
/* Version History:                                                                               */
/*  0.9.4 - Created                                                                               */
/**************************************************************************************************/
function hsmember_configure_options_defaults() {
  return apply_filters("hsmember_default_options",array("options_version" => "1.0",
                                                        "login_required_page" => "",
                                                        "blog_create_access" => 0,
                                                        "new_activation" => 1));
} // end of hsmember_configure_options_defaults()

/**************************************************************************************************/
/* Function to validate the option values in $GLOBALS["_HSMEMBER_"].                              */
/* Return Value:                                                                                  */
/*  The validated options.                                                                        */
/* Version History:                                                                               */
/*  0.9.4 - Created                                                                               */
/**************************************************************************************************/
function hsmember_configure_options_validate() {
  $def = hsmember_configure_options_defaults();
  foreach ($GLOBALS["_HSMEMBER_"]["o"] as $key => &$value) {
    if (!is_array ($value))
      $value = trim (stripslashes ($value));
    else /* A string, or an array of strings. */
      foreach ($value as $k => $v)
        $value[$k] = trim (stripslashes ($v));
    if ($key === "options_version" && (!is_string ($value) || !is_numeric ($value)))
      $value = $default_options[$key];
    else if ($key === "login_required_page" && (!is_string ($value) || !is_numeric ($value)))
      $value = $default_options[$key];
    else if ($key === "blog_create_access" && (!is_numeric ($value) || $value<0 || $value>4))
      $value = $default_options[$key];
    else if ($key === "new_activation" && (!is_numeric ($value)))
      $value = $default_options[$key];
  }
  return $GLOBALS["_HSMEMBER_"]["o"];
} // end of hsmember_configure_options_validate()

/**************************************************************************************************/
/* Function to load the options from the data tabkles into the $GLOBALS['_HSMEMBER_'] array.      */
/*  The data will also be checked for data integrity and set to default values where needed.      */
/* Version History:                                                                               */
/*  0.9.4 - Created                                                                               */
/**************************************************************************************************/
function hsmember_configure_options_init() {
  $def = hsmember_configure_options_defaults();
  $GLOBALS["_HSMEMBER_"]["o"] = array_merge($def,(array)get_option("hsmember_options"));
  hsmember_configure_options_validate();
  do_action("hsmember_options_load");
} // end of hsmember_configure_options_init()

// Configure & validate all of the plugin options; and set their defaults.
hsmember_configure_options_init();
?>